Added header and description
PolicyEngine/us-marriage-incentive pull request #10
Opened 2024-01-15 20:36 UTC by ThapeloMasasa

This pull request address issue #5

2024-01-16 17:21 UTC, PavelMakarchuk requested changes

2024-01-16 17:21 UTC, PavelMakarchuk commented on app.py
> +header = st.header("Marriage Incentive App")
```suggestion
header = st.header("Marriage Incentive Calculator")
```

2024-01-16 17:21 UTC, PavelMakarchuk commented on app.py
> +header_description = st.write("Streamlit app evaluates penalties and bonuses based on the state and marriage status of an individual")
```suggestion
header_description = st.write("This application evaluates marriage penalties and bonuses of couples, based on state and individual employment income")
```

2024-01-16 17:21 UTC, PavelMakarchuk commented on app.py
> +repo_link = st.markdown("Here is the Repo of the application <a href='https://github.com/PolicyEngine/us-marriage-incentive'>link</a>", unsafe_allow_html=True)
```suggestion
repo_link = st.markdown("This application utilizes the policyengine API <a href='https://github.com/PolicyEngine/us-marriage-incentive'>link</a>", unsafe_allow_html=True)
```

2024-01-17 21:05 UTC, PavelMakarchuk approved these changes

2024-01-17 22:47 UTC, MaxGhenis approved these changes

2024-01-17 22:47 UTC, merged