Add a dropdown to the heatmap to select if the heatmap should display…
PolicyEngine/us-marriage-incentive pull request #56
Opened 2024-04-16 23:42 UTC by ThapeloMasasa

benefits, taxes, credits or net income drop down menu for heat map

Fixes #54

2024-04-16 23:42 UTC, ThapeloMasasa commented
Here is the demo: 

https://github.com/PolicyEngine/us-marriage-incentive/assets/73863365/702c8d81-d7ed-4b57-9dd6-d63edad6ac86

2024-04-25 00:22 UTC, ThapeloMasasa commented
https://github.com/PolicyEngine/us-marriage-incentive/assets/73863365/405b2608-3a30-43f9-9c36-c11e4faec02f

2024-04-29 09:38 UTC, PavelMakarchuk requested changes

2024-04-29 09:38 UTC, PavelMakarchuk commented on app.py
> +    delta_percent = [(x - y) / x if y != 0 and x != 0 else 0 for x, y in zip(married_programs, separate)]
```suggestion
    delta_percent = [(x - y) / x if x != 0 and x != 0 else 0 for x, y in zip(married_programs, separate)]
```

2024-04-29 09:38 UTC, PavelMakarchuk commented on app.py
> +@st.cache_data()
need to investigate why the heatmap output differs from the table output - I believe the table is mostly aligned with the App but the heatmap seems off in all of the cases

2024-05-06 16:07 UTC, PavelMakarchuk commented
need to fix conflicts

2024-05-07 03:27 UTC, merged