Remove the heatmap and fix the table tabs to reflect benefits, credits and taxes
PolicyEngine/us-marriage-incentive pull request #80
Opened 2024-06-01 01:44 UTC by PavelMakarchuk

2024-06-01 13:23 UTC, MaxGhenis requested changes
also run black for formatting

2024-06-01 13:23 UTC, MaxGhenis commented on app.py
> +us_territories = {
capitalize constants
```suggestion
US_TERRITORIES = {
```

2024-06-01 13:23 UTC, MaxGhenis commented on app.py
> +    "This application utilizes <a href='https://github.com/PolicyEngine/us-marriage-incentive'>the policyengine API</a>",
The repo's code is in the upper right of all streamlit apps. Was something not working with the normal markdown link syntax? No longer need `unsafe_allow_html=True`.
```suggestion
    "This application utilizes the [`policyengine-us` Python package](https://github.com/policyengine/policyengine-us).",
```

2024-06-01 13:23 UTC, MaxGhenis commented on app.py
> +    resource_path_federal = "parameters/gov/irs/credits/refundable.yaml"
the way we do this in the web app is to navigate the `adds` features of the variables: https://github.com/PolicyEngine/policyengine-app/blob/7e3b1b6117de799f7ef19d199138ea96af93e971/src/pages/household/output/NetIncomeBreakdown.jsx#L176

@nikhilwoodruff do you have an example of doing this in Python?

2024-06-01 13:23 UTC, MaxGhenis commented on app.py
> +    benefits_dic = {}
by convention
```suggestion
    benefits_dict = {}
```

2024-06-01 13:23 UTC, MaxGhenis commented on app.py
> +    formatted_benefits_married = list(
make this a function since applying 4x

2024-06-01 13:23 UTC, MaxGhenis commented on app.py
> +        "Net Income",
```suggestion
        "Net income",
```

2024-06-01 13:23 UTC, MaxGhenis commented on app.py
> +    taxes_before_refundable_credits = list(programs[0][-3].keys())
you can avoid code duplication by creating a single dataframe with all the variables you want across the three situations, and adding a column for the category (Total, Taxes before refundable credits, Refundable credits, Benefits) then when displaying the breakdown filtering the table on that category. Then you can calculate absolute and relative differences in one dataframe command.

2024-06-02 21:15 UTC, PavelMakarchuk commented
> I will not merge this before adding back the heatmap - using the PR to get intermediate feedback for the format

Decided to merge to match the PR and limit PR complexity for review -> Will add heatmap in separate PR

2024-06-02 22:10 UTC, merged