Add_heatmap_back
PolicyEngine/us-marriage-incentive pull request #86
Opened 2024-06-13 03:59 UTC by ThapeloMasasa

Fixes #85

2024-06-24 11:59 UTC, PavelMakarchuk requested changes

2024-06-24 11:59 UTC, PavelMakarchuk commented on app.py
> +    "spouse": spouse_disability
remove child disability here

2024-06-24 11:59 UTC, PavelMakarchuk commented on app.py
> +    "spouse": spouse_disability
and elsewhere

2024-06-24 12:00 UTC, PavelMakarchuk commented
Can we validate heatmap results in the spreadsheet as well? Add a column for the heatmap match

2024-06-24 12:03 UTC, PavelMakarchuk commented on app.py
> +    return np.array(net_income)  # Ensure the result is a numpy array
can we store the incomes in pandas dataframes (three total)

2024-07-01 01:34 UTC, PavelMakarchuk requested changes

2024-07-01 01:34 UTC, PavelMakarchuk commented on app.py
> +}
duplicate

2024-07-09 18:07 UTC, ThapeloMasasa commented
Here is the video for  how it works

https://github.com/PolicyEngine/us-marriage-incentive/assets/73863365/2250b04f-d9bd-4a31-adf3-699eed6c6dcb

2024-07-09 21:46 UTC, PavelMakarchuk commented
Can you adjust the labels when hovering over the values? I think we are using the breakdown categories to represent income, e.g.:
![image](https://github.com/PolicyEngine/us-marriage-incentive/assets/110687043/11c25b47-a2d2-4148-9930-4d23b1dd886a)
Here it should say: 
Head Employment income:
Spouse Employment income:
Tax Credit change:

2024-07-15 13:33 UTC, merged